"""add gpxfile_track_id field

Revision ID: 0040d68ed9cb
Revises: 60868f9a26c3
Create Date: 2020-08-24 16:08:15.191761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0040d68ed9cb'
down_revision = '60868f9a26c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('gpxfile_track_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'gpxfile_track_id')
    # ### end Alembic commands ###
