"""add thumbnail field

Revision ID: 31237007b92f
Revises: 0040d68ed9cb
Create Date: 2020-08-25 11:19:44.511849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31237007b92f'
down_revision = '0040d68ed9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('thumbnail', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'thumbnail')
    # ### end Alembic commands ###
